/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 3 "test.i"
static char wp[9][4]  = 
#line 3 "test.i"
  { {        (char)1,        (char)2,        (char)3,        (char)4}, 
   {        (char)1,        (char)2,        (char)3,        (char)4}, 
   {        (char)1,        (char)2,        (char)3,        (char)4}, 
   {        (char)1,        (char)2,        (char)3,        (char)4}, 
   {        (char)1,        (char)2,        (char)3,        (char)4}, 
   {        (char)1,        (char)2,        (char)3,        (char)4}, 
   {        (char)1,        (char)2,        (char)3,        (char)4}, 
   {        (char)1,        (char)2,        (char)3,        (char)4}, 
   {        (char)1,        (char)2,        (char)3,        (char)4}};
#line 2015
extern int ( /* missing proto */  g)() ;
#line 2013 "test.i"
int main(void) 
{ 
  int *p ;
  int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;

  {
  {
  {
#line 2015
  while (1) {
    while_continue___1: /* CIL Label */ ;
    while_continue: /* CIL Label */ ;
    {
    {
#line 2015
    tmp = g();
    }
    }
#line 2015
    if (! tmp) {
#line 2015
      goto while_break;
    }
#line 2016
    p = (int *)(wp);
#line 2017
    p ++;
  }
  while_break___1: /* CIL Label */ ;
  }
  while_break: /* CIL Label */ ;
  }
  {
  {
#line 2019
  tmp___0 = g();
  }
#line 2019
  *(p + tmp___0) = 4;
  }
  {
  {
#line 2020
  while (1) {
    while_continue___2: /* CIL Label */ ;
    while_continue___0: /* CIL Label */ ;
    {
    {
#line 2020
    tmp___2 = g();
    }
    }
#line 2020
    if (! tmp___2) {
#line 2020
      goto while_break___0;
    }
    {
    {
#line 2021
    tmp___1 = g();
    }
#line 2021
    *(p + tmp___1) = 4;
    }
  }
  while_break___2: /* CIL Label */ ;
  }
  while_break___0: /* CIL Label */ ;
  }
#line 2023
  return (0);
}
}
