/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 8
extern int ( /* missing proto */  airac_observe)() ;
#line 1 "test.c"
int main(void) 
{ 
  int p ;
  int buf[10] ;
  int idx ;

  {
  {
#line 4
  p = 614512ULL;
#line 7
  idx = 614512ULL;
#line 8
  airac_print (idx);
  airac_observe(buf, idx);
#line 9
  p = 614512ULL;
  }
#line 10
  return (0);
}
}
